on:
  workflow_call:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout calling repository code
        uses: actions/checkout@v4

      - name: Run Semgrep scan
        env:
          SEMGREP_SEND_METRICS: off
        run: |
          semgrep scan \
            --config=p/security-audit \
            --sarif \
            --output=semgrep.sarif

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif


